# 플러그인 설정 파일
# 이 파일을 수정하여 플러그인 동작을 커스터마이징할 수 있습니다

# 기본 설정
settings:
   # 플러그인 활성화 여부
   enabled: true

   # 디버그 모드
   debug: false

   # 메시지 설정
   messages:
      prefix: "&8[&6플러그인&8] &r"
      no-permission: "&c권한이 없습니다!"
      player-only: "&c이 명령어는 플레이어만 사용할 수 있습니다!"

# 데이터베이스 설정 (필요한 경우)
database:
   type: "sqlite" # sqlite, mysql, postgresql
   host: "localhost"
   port: 3306
   database: "minecraft_plugin"
   username: "root"
   password: "password"
